title: Hannah Sun
description: Hannah Sun's portfolio

url: "https://xhsun.github.io"
baseurl: ""

#Links
image: "/assets/img/"
logo: "/assets/img/logo.png"
#Externals
github: "https://github.com/xhsun"
googleapis: "https://fonts.googleapis.com/"
header_font: "css?family=Nova+Mono"
all_font: "css?family=Allura|Geo|Nova+Mono|Yeseva+One"

# Build settings
theme: minima

sass:
  sass_dir: _sass
  style: compressed

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: <!--MORE-->

kramdown:
  input: GFM

# Defaults
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

gems:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-octicons

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
